services:
  mediso_dev_db:
    image: postgres:alpine
    ports: 
     - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mediso_dev_db:/var/lib/postgresql/data

  mediso:
    image: ghcr.io/riteshbhoskar/mediso:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - .env
    ports:
     - 3000:3000
    depends_on:
     - mediso_dev_db

  wss-server:
    image: ghcr.io/riteshbhoskar/mediso-wss-server:latest
    build:
      context: ./wss-server
      dockerfile: Dockerfile
    env_file:
     - .env
    ports: 
     - 8080:8080
    depends_on:
     - mediso

volumes:
  mediso_dev_db: